### ISSUE TITLE
Windows binary downloads corrupted (need to call `tempfile.binmode`)

### ISSUE THREAD

**Issue by karlmdavis** [lwf/puppet-remote_file#15]
On Windows, I've discovered that largish binary downloads end up corrupted, e.g. ZIPs that download and look mostly correct, but can't actually be opened.

The solution is pretty simple, just add a call to `tempfile.binmode` in `lib/puppet/provider/remote_file/ruby.rb`, e.g.:
```
    # ...
    begin
      tempfile = Tempfile.new('remote_file')
      tempfile.binmode  # <-- Fixes the problem. Huzzah!
      response = http(uri, tempfile)
    # ...
```

As a side note, it'd also be super helpful if you could push the 0.2.1 release, and/or whatever release you cut after this fix, to Puppet Forge (the latest there seems to just be 0.2.0).

**Comment by lwf** [comment]
Should be fixed in master now. Will push a new version to Puppet Forge soon enough. Thanks for the report!

**Comment by lwf** [comment]
0.2.2 is on the Puppet Forge now, which should resolve this (I haven't tested it though as I have no Windows systems to test it on).
