### ISSUE TITLE
Ability to use hash (checksum) functions other than MD5

### ISSUE THREAD

**Issue by pkkm** [lwf/puppet-remote_file#17]
MD5 is good for protecting against transmission errors, but [not against MITM attacks](http://www.mathstat.dal.ca/~selinger/md5collision/) (which can be executed easily on many public networks). An option to use SHA-256 or SHA-512 hashes would enable writing more secure Puppet manifests.

**Comment by lwf** [comment]
Definitely a good suggestion. Not sure when I'd be able to get to it though as I no longer use Puppet on a daily basis. PRs welcome.

**Comment by lwf** [comment]
This turned out to be easier than I had thought. You can now specify `checksum_type` when using latest master. Defaults to md5; all algorithms supported by the core File type can be specified.

**Comment by pkkm** [comment]
Thanks!
