### ISSUE TITLE
Submit for Puppet Approved status

### ISSUE THREAD

**Issue by reidmv** [lwf/puppet-remote_file#19]
@lwf with your permission, I would like to submit this module to the review process for [Puppet Approved](https://forge.puppetlabs.com/approved). `remote_file` is the best solution for ensuring files are retrieved from remote sources that I know of, given its combination of excellent user experience and lightweight requirements to use.

The process to submit for approval is simple and involves creating at ticket at https://tickets.puppetlabs.com/browse/MODULES. I'm happy to take on the work of submitting the ticket and walking it through the process. I would be very happy to see this module receive the approved designation. Please let me know if this is amenable to you. If you would prefer to submit the ticket yourself that also works well for me.

Thank you for creating this module, and for being so responsive to pull requests!

**Comment by lwf** [comment]
I'd be fine with this. I'm also fine with you taking care of the submission process if you don't mind (you probably know the code better than I do at this point).

**Comment by reidmv** [comment]
@lwf Thanks! I've submitted https://tickets.puppetlabs.com/browse/MODULES-2038 and I'll watch it to make sure any requests are responded to and keep it moving forwards.

**Comment by reidmv** [comment]
@lwf to be eligible for Puppet Approved status we need a 1.0.0 release. I suspect the module is ready for this already, and it would just need to be promoted from 0.x. Is there any additional work or design you would like to have done before cutting a 1.0.0 release of this module?

**Comment by lwf** [comment]
I'll cut a 1.0 release soon and update this issue when it's done.

**Comment by lwf** [comment]
Have uploaded 1.0.0.

**Comment by reidmv** [comment]
Awesome - I'm told it will be reviewed at the scheduled triage meeting next week.

**Comment by reidmv** [comment]
@lwf w00t! https://forge.puppetlabs.com/lwf/remote_file is now a Puppet-approved Forge module! :+1:

**Comment by lwf** [comment]
Nice. Thanks for all the assistance in making it happen.
