### ISSUE TITLE
latest option is not supporting

### ISSUE THREAD

**Issue by hussainaphroj** [lwf/puppet-remote_file#21]
Hi,

I have a requirement to download a file from S3 bucket only when that file got modified, I have found your code very helpful but while using with ensure=>latest, throwing below error:

Remote_file[/mnt/abc]/ensure: change from 2015-07-06T08:25:17-04:00 to latest failed: undefined method `close' for nil:NilClass

remote_file { '/mnt/abc':
        ensure   => latest,
        source   => 'https://s3.amazonaws.com/abc/abc',
      }

I have tested with ensure=>present too but it is downloading only first time, I have modified the file on S3 and ran puppet , The latest file didn't get pulled .
 checksum attribute is also not getting supported.

Any help will be appreciated.
Thanks,
Afroz

**Comment by lwf** [comment]
Hey,

Do you have a URL which I could use to reproduce this issue?

**Comment by hussainaphroj** [comment]
Hi,

I am afraid to share it since it is customer specific. Can you please create a file on S3 and test it.

Thanks,
Afroz Hussain

**Comment by tinsjourney** [comment]
Hi,

Got the same issue, but only on Redhat 6. With Redhat 7 there is no problem.
RHEL6 :
* ruby-1.8.7
* puppet-3.7.1
RHEL7 :
* ruby-2.0.0.353
* puppet-3.7.1

I don't use S3, just a http server on my lan.

Stephane

**Comment by tinsjourney** [comment]
Found why it wasn't working for me.
The File::NULL is new to Ruby 1.9.3, but in RHEL6 it's Ruby 1.8.7

So the problem is with line 78
null = File.open(File::NULL)
1.8 => uninitialized constant File::NULL

Looking at ruby backport
Backport 1.8 : (https://github.com/marcandre/backports)

adding the following will fix the issue.
unless File.const_defined? :NULL
  module File::Constants
    platform = RUBY_PLATFORM
    platform = RbConfig::CONFIG['host_os'] if platform == 'java'
    NULL =  case platform
            when /mswin|mingw/i
              'NUL'
            when /amiga/i
              'NIL:'
            when /openvms/i
              'NL:'
            else
              '/dev/null'
            end
  end
end                 

and it works !!!!

**Comment by lwf** [comment]
Ruby 1.8 is not supported by this module. This is by design; 1.8 has been EOL for 2+ years now.
