### ISSUE TITLE
uninitialized constant FILE_PARAMS on ruby 1.8.7

### ISSUE THREAD

**Issue by liamjbennett** [lwf/puppet-remote_file#24]
Could not autoload puppet/type/remote_file: uninitialized constant FILE_PARAMS

**Comment by lwf** [comment]
Hey,

As mentioned in the README, Ruby 1.8.7 is not supported. Please try to reproduce with 1.9 or later.

**Comment by liamjbennett** [comment]
I belive this is a 1.8.7 issue only. Closing for now.

**Comment by lwf** [comment]
Not sure if this is still relevant to you, but changes as of most recent master enable use of Ruby 1.8 with remote_file.

**Comment by liamjbennett** [comment]
Good news to hear.
