### ISSUE TITLE
Could not evaluate: no implicit conversion of true into String

### ISSUE THREAD

**Issue by alexfouche** [lwf/puppet-remote_file#25]
Hi,
the commit e37d634 broke my run. I am using Puppet 4 opensource

    (...) Remote_file[/etc/yum.repos.d/passenger.repo]: Could not evaluate: no implicit conversion of true into String

when i used 

        remote_file { '/etc/yum.repos.d/passenger.repo':
                ensure  => present,
                source  => 'https://oss-binaries.phusionpassenger.com/yum/definitions/el-passenger.repo',
        }

**Comment by lwf** [comment]
Should be fixed as of the most recent revision of master.
